# site settings
title: 생물정보학과 인공지능 그리고 잡다한 지식
subtitle: by scarleaf
email: youremailaddress@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/scarleaf.github.io/" # the subpath of your site, e.g. /blog
url: https://scarleaf.github.io/ # the base hostname & protocol for your site
author: Woong Jeong
street_address: 
city: 성남시
state: 
zip_code: 
country: 대한민국
phone: +82-10-6450-6850

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: 
facebook_url: https://www.facebook.com/scarleaf
github_url: https://github.com/scarleaf
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/vkseydnjsakdmf/
linkedin_url: https://www.linkedin.com/in/woong-jeong-a29109aa/
pinterest_url: 
slack_url: 
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
